MackPortfolio/MackPortfolio/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MackPortfolio.Extensions;
using MackPortfolio.DAL.Interfaces;
using MackPortfolio.DAL.Repositories;
using MackPortfolio.DAL.Interfaces.Models;

namespace MackPortfolio.Controllers
{
    public class ActivityController : BaseController
    {
        private IActivityRepository rep;
        // GET: Activity
        public ActionResult Index()
        {
            //rep = new ActivityRepository();
            //var list = rep.GetList();
            return View();
        }

        public ActionResult _activityList()
        {
            rep = new ActivityRepository();
            var list = rep.GetList();
            return PartialView(list);
        }

        public JsonResult _activityListJson()
        {
            rep = new ActivityRepository();
            var list = rep.GetList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        // GET: /Activity/Details/5
        public ActionResult Details(string page, Guid? id, string urlparam)
        {
            rep = new ActivityRepository();
            if (id == null && page == "Details")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var article = rep.GetArticle(id);
            if (article == null)
            {
                if (page == "Details")
                {
                    return HttpNotFound();
                }
                article = new ActivityViewModel();
            }
            ViewBag.page = page;
            return View(page, article);
        }

        // POST: /Activity/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HostBy,HostEmail,HostPhone,EventDate,ImageUrl,Title,Summary,BodyHtml,UrlParameter,Created,Modified,IsActive,Address,Lat,Lng,LogMessages")] 
            ActivityViewModel activity, FormCollection fc)
        {
            rep = new ActivityRepository();
            var file = Request.Files.AllKeys.Any() ? Request.Files[0] : null;
            if (ModelState.IsValid)
            {
                activity = rep.CreateArticle(activity, file, Server);
                return RedirectToAction("Index");
            }

            ViewBag.page = "Modify";
            return View("Modify", activity);
        }

        // POST: /Activity/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HostBy,HostEmail,HostPhone,EventDate,ImageUrl,Title,Summary,BodyHtml,UrlParameter,Created,Modified,IsActive,Address,Lat,Lng,LogMessages")] 
            ActivityViewModel activity, FormCollection fc)
        {
            rep = new ActivityRepository();
            var file = Request.Files.AllKeys.Any() ? Request.Files[0] : null;

            if (ModelState.IsValid)
            {
                activity = rep.EditArticle(activity, file, Server);
                return RedirectToAction("Index");
            }

            ViewBag.page = "Modify";
            return View("Modify", activity);
        }

        // GET: /Activity/Delete/5
        public ActionResult Delete(Guid? id)
        {
            rep = new ActivityRepository();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var activity = rep.GetArticle(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: /Activity/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            rep = new ActivityRepository();
            rep.DeleteArticle(id);
            return RedirectToAction("_activityList");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                rep.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MackPortfolio/MackPortfolio/Controllers/PaletteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MackPortfolio.Controllers
{
    public class PaletteController : BaseController
    {
        // GET: Palette
        public ActionResult Index()
        {
            return View();
        }
    }
}

MackPortfolio/MackPortfolio/Views/Shared/_Layout.cshtml
@{
    var brw = Request.Browser;
    var baseModel = ViewBag.BaseModel as MackPortfolio.Models.ActionLayoutModel;
    var mainTitle = baseModel.MainTitle;
}
<!DOCTYPE html>
<html class="@Request.GetHtmlClass()" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | @(mainTitle)</title>
    <meta name="title" content="@(ViewBag.Title) | @(mainTitle)" />
    <meta name="keywords" content="Portfolio, Resume, HTML5, CSS3, JavaScript, jQuery, Web Development, Responsive Design, Single Page Application" />
    <meta name="author" content="likwidmack.com" />
    @Html.Partial("_headscripts")
    @RenderSection("styles", required: false)
</head>
<body>
    <div id="mainapp" class="page">
        <header>@Html.Partial("_header", baseModel)</header>
        <div id="mainbody" class="container body-content">
            @RenderBody()
        </div>
        <footer class="main-footer">
            @Html.Partial("_footer", baseModel)
        </footer>
    </div>
    @Html.Partial("_footscripts", baseModel)
    @RenderSection("scripts", required: false)
</body>
</html>

MackPortfolio/MackPortfolio/Views/Shared/_footer.cshtml
@model MackPortfolio.Models.ActionLayoutModel
<div class="row">
    <div class="small-11 small-centered columns">
        <ul class="inline-list">
            <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
            <li>@Html.ActionLink("Resume", "Index", "About", new { area = "" }, null)</li>
            <li>@Html.ActionLink("Canvas", "Index", "Palette", new { area = "" }, null)</li>
            <li>@Html.ActionLink("Activities", "Index", "Activity", new { area = "" }, null)</li>
            <li>@Html.ActionLink("Codes", "Index", "Random", new { area = "" }, null)</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
        </ul>
    </div>
</div>
<p>
    &copy; @DateTime.Now.Year - @(Model.MainTitle), 
    <strong>Work In Progress</strong> Last Modified: <span id="RetrieveLinkerTimestamp">@Model.WIP</span>
</p>
@if (Model.isDebugMode)
{ <div id="isDebugMode" class="alert alert-box"><span>Debug Enabled</span></div> }

MackPortfolio/MackPortfolio/Views/Shared/_footscripts.cshtml
@model MackPortfolio.Models.ActionLayoutModel

<script src="http://code.jquery.com/ui/1.11.1/jquery-ui.js" type="text/javascript"></script>
<script src="http://code.jquery.com/color/jquery.color.plus-names-2.1.2.min.js" type="text/javascript"></script>

@Scripts.Render("~/libs/knockout")
<script src="http://cdnjs.cloudflare.com/ajax/libs/knockout-validation/1.0.2/knockout.validation.js" type="text/javascript"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/knockout.mapping/2.4.1/knockout.mapping.js" type="text/javascript"></script>

<script src="http://rniemeyer.github.io/knockout-kendo/js/knockout-kendo.min.js" type="text/javascript"></script>

@if (Request.IsIE())
{
    if (Request.CompareVersion(x => x < 9))
    {
        <script src="@Url.Content("~/Scripts/rem-fix.js")" type="text/javascript"></script>
        if (Request.CompareVersion(x => x < 7))
        {
            <script src="http://cdnjs.cloudflare.com/ajax/libs/dd_belatedpng/0.0.8/dd_belatedpng.min.js" type="text/javascript"></script>
            <script type="text/javascript">DD_belatedPNG.fix('img, .png_bg');</script>
        }
    }
}
@Scripts.Render("~/libs/ko", "~/libs/site","~/libs/foundation")
<script type="text/javascript">
    if ('undefined' === typeof main) {
        var main = document.getElementById("mainapp");
    }
    main.isDebugMode = Boolean('@Model.isDebugMode');
    $(document).foundation();
</script>

MackPortfolio/MackPortfolio/Views/Shared/_header.cshtml
@model MackPortfolio.Models.ActionLayoutModel
<nav class="top-bar header" data-topbar>
    <ul class="title-area">
        <li class="name">
            <h1><a href="@Url.Action("Index", "Home")" class="clipped flip">Code Samples</a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>
    <section class="top-bar-section">
        <ul class="right">
            <li class="divider"></li>
            <li>@Html.ActionLink("Resume", "About", "Home")</li>
            <li class="divider"></li>
            <li>@Html.ActionLink("Canvas & Palette", "Index", "Palette")</li>
            <li class="divider"></li>
            <li>@Html.ActionLink("Activities", "Index", "Activity")</li>
            <li class="divider"></li>
            <li>@Html.ActionLink("Random Codes", "Index", "Random")</li>
            @* Work in Progress [NOT READY FOR VIEWING] *@
            @*<li class="divider"></li>
                <li>@Html.ActionLink("Galleries", "Index", "Gallery")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
        </ul>
        @*<ul class="left">
            <li class="divider"></li>
            <li><span class="warning label">Work In Progress: @(Model.WIP)</span></li>
        </ul>*@
    </section>
</nav>

MackPortfolio/MackPortfolio/Views/Shared/_headscripts.cshtml
<link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />
@Styles.Render("~/Content/css", "~/Content/kendo/2014.2.716/css")
@Scripts.Render("~/libs/modernizr")
<script>
    Modernizr.addTest('backgroundcliptext', function () {
        var testEl = document.createElement('div');
        var supportsWebkitBackgroundClipText = typeof testEl.style.webkitBackgroundClip !== "undefined"
            && (testEl.style.webkitBackgroundClip = "text", testEl.style.webkitBackgroundClip === "text");
        return supportsWebkitBackgroundClipText;
    });
</script>

@Scripts.Render("~/libs/jquery")
@if (Request.IsIE(9))
{
    @Scripts.Render("~/libs/jqueryLegacyIE", "~/libs/respond")
    <script src="http://s3.amazonaws.com/nwapi/nwmatcher/nwmatcher-1.2.5-min.js"></script>
    <script src="http://html5base.googlecode.com/svn-history/r38/trunk/js/selectivizr-1.0.3b.js" type="text/javascript"></script>
}
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/mootools/1.4.5/mootools-core-full-compat-yc.js" type="text/javascript"></script>
@Scripts.Render("~/libs/kendo")